services:
  api:
    container_name: microblog-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    platform: linux/amd64
    environment:
      PORT: 8081
      NODE_ENV: production
    ports:
      - '8081:8081'
    networks:
      - microblog-network

  web:
    container_name: microblog-web
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      VITE_API_BASE_URL: http://localhost:8081/api/v1
    ports:
      - '5173:5173'
    depends_on:
      - api
    networks:
      - microblog-network

networks:
  microblog-network:
    driver: bridge
